name: Deploy Iraklion Micrososervice (Child)
on: 
  workflow_dispatch:
    inputs:
      heracles_alias:
        description: 'Heracles Alias'     
        required: true
      iraklion_alias:
        description: 'Iraklion Alias'     
        required: true
env:
   HERACLES_PAT: ${{ secrets.HERACLES_PAT }}
   HERACLES_ALIAS: ${{ github.event.inputs.heracles_alias }}
   IRAKLION_ALIAS: ${{ github.event.inputs.iraklion_alias }}  
jobs:
  job1:
    name: Build Iraklion Container and push to ACR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{env.HERACLES_ALIAS}}acr.azurecr.io
        username: ${{env.HERACLES_ALIAS}}acr
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        docker build -f iraklion/Dockerfile -t ${{env.HERACLES_ALIAS}}acr.azurecr.io/heracles/iraklion:${{github.run_number}} .
        docker push ${{env.HERACLES_ALIAS}}acr.azurecr.io/heracles/iraklion:${{github.run_number}}
  job2:
    name: Associate Iraklion container with web app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{env.HERACLES_ALIAS}}acr.azurecr.io
        username: ${{env.HERACLES_ALIAS}}acr
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        az webapp config container set --docker-custom-image-name ${{env.HERACLES_ALIAS}}acr.azurecr.io/zodiac/limone-api:${{github.run_number}} \
             --docker-registry-server-password ${{ secrets.ACR_PASSWORD }} \
             --docker-registry-server-url https://${{env.HERACLES_ALIAS}}acr.azurecr.io \
             --docker-registry-server-user ${{env.HERACLES_ALIAS}}acr \
             --name ${{env.IRAKLION_ALIAS}}-api \
             --resource-group ${{env.IRAKLION_ALIAS}}-rg

        az webapp log config --docker-container-logging filesystem \
             --name ${{env.IRAKLION_ALIAS}}-api \
             --resource-group ${{env.IRAKLION_ALIAS}}-rg
